"""Foundry harness rendering (Phase 2, step 2; attack upgrade Phase 1).

Turns (contract source + invariants) into a self-contained Foundry project:

- ``src/<Contract>.sol`` — the target source, verbatim.
- ``test/Invariant.t.sol`` — the harness test contract.
- ``test/attackers/*.sol`` — generated malicious contracts (attack mode).
- ``foundry.toml`` — hardened (``ffi = false``, ``fs_permissions = []``)
  with the ``[invariant]`` profile wired to the campaign bounds and the
  campaign seed plumbed through (``forge --fuzz-seed`` / ``[fuzz] seed``
  plus an on-chain bandit PRNG constant, so campaigns reproduce).

Two rendering modes:

- **Attack mode** (default, ``FuzzBounds.attack_enabled``): the old
  simulator could only make simple moneyless direct calls, so reentrancy,
  value-flow bugs, and time-dependent logic were structurally invisible.
  The attack harness teaches it to actually attack: an ``AttackHandler``
  contract (the only contract deployed in ``setUp()``, hence the only
  thing Foundry's invariant engine fuzzes) exposes
  *value-carrying* actions for every target function (ETH amounts drawn
  from the fuzzer's input space, clamped to ``attack_max_value_wei``),
  *time-warp* actions (``vm.warp``/``vm.roll`` via cheatcodes, no
  forge-std needed), *multi-step heist* actions
  (deposit -> warp -> reenter -> drain inside one call), and an
  *adaptive* action running an on-chain epsilon-greedy bandit over the
  attack modes, reinforced by real extracted profit. Malicious contracts
  (reentrancy attacker, approval drainer, donation attacker) are
  generated by :mod:`web3guard.invariants.attackers`, deployed by the
  handler, and driven *through*. A harness-level invariant,
  ``invariant_attacker_no_profit``, asserts the attackers never hold more
  ETH than they were funded with — a violation is a machine-checked
  exploit with the exact call sequence as PoC.
- **Plain mode** (``attack_enabled=False``): the legacy Phase-2 rendering
  — Foundry's invariant engine directly fuzzes the target deployed in
  ``setUp()`` with moneyless calls. Kept for baselining and for targets
  where the attack harness cannot compile.

The renderer is deliberately forge-std-free, so a campaign needs no
dependency downloads — only ``forge`` and a solc download on first run.

The module is unit-testable WITHOUT forge: rendering is pure string
building. A per-language renderer registry lets Phase 6 plug in
Move/Cairo/Clarity harnesses later.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path

from web3guard.invariants import attackers as _attackers
from web3guard.invariants import strategies as _strategies
from web3guard.invariants.models import FunctionSig, FuzzBounds, Invariant

LOGGER = logging.getLogger("web3guard.invariants.harness")

# ---------------------------------------------------------------------------
# Source introspection (regex-based; good enough for harness generation)
# ---------------------------------------------------------------------------

_CONTRACT_RE = re.compile(r"^\s*contract\s+(\w+)", re.MULTILINE)
_PRAGMA_RE = re.compile(r"^\s*pragma\s+solidity\s+([^;]+);", re.MULTILINE)
_FUNC_RE = re.compile(
    r"function\s+(\w+)\s*\(([^)]*)\)\s*"
    r"((?:external|public|internal|private)\s*)?"
    r"((?:payable|view|pure)\s*)?",
)


def extract_contract_name(source: str) -> str:
    """Return the first concrete contract name, defaulting to "Target"."""
    m = _CONTRACT_RE.search(source)
    return m.group(1) if m else "Target"


@dataclass
class ContractBlock:
    """One top-level contract/interface/library block with its body span."""

    name: str
    kind: str  # "contract" | "interface" | "library" | "abstract"
    start: int  # index of the opening brace
    end: int  # index just past the matching closing brace
    body: str  # source between the braces


_CONTRACT_DEF_RE = re.compile(
    r"\b(?:(abstract)\s+)?contract\s+(\w+)"
    r"|\binterface\s+(\w+)"
    r"|\blibrary\s+(\w+)"
)


def _code_mask(source: str) -> list[bool]:
    """Mark each character as code (True) vs comment/string (False)."""
    mask = [True] * len(source)
    i, n = 0, len(source)
    while i < n:
        c = source[i]
        nxt = source[i + 1] if i + 1 < n else ""
        if c == "/" and nxt == "/":
            j = source.find("\n", i)
            j = n if j == -1 else j
            for k in range(i, j):
                mask[k] = False
            i = j
        elif c == "/" and nxt == "*":
            j = source.find("*/", i + 2)
            j = n if j == -1 else j + 2
            for k in range(i, j):
                mask[k] = False
            i = j
        elif c in ("\"", "'"):
            j = i + 1
            while j < n:
                if source[j] == "\\":
                    j += 2
                    continue
                if source[j] == c:
                    j += 1
                    break
                j += 1
            for k in range(i, min(j, n)):
                mask[k] = False
            i = j
        else:
            i += 1
    return mask


def split_contracts(source: str) -> list[ContractBlock]:
    """Split source into top-level contract/interface/library blocks.

    Brace matching is comment/string-aware, so braces inside comments or
    string literals cannot corrupt the spans. Nested definitions are
    attributed to the outermost block.
    """
    mask = _code_mask(source)
    blocks: list[ContractBlock] = []
    for m in _CONTRACT_DEF_RE.finditer(source):
        if not mask[m.start()]:
            continue
        if m.group(2) is not None:
            name, kind = m.group(2), "abstract" if m.group(1) else "contract"
        elif m.group(3) is not None:
            name, kind = m.group(3), "interface"
        else:
            name, kind = m.group(4), "library"
        # find the opening brace after the match (skipping inheritance list)
        i = m.end()
        depth = 0
        open_idx = -1
        while i < len(source):
            if not mask[i]:
                i += 1
                continue
            if source[i] == "{":
                open_idx = i
                depth = 1
                i += 1
                break
            if source[i] == ";":
                break  # forward declaration / import-ish; no body
            i += 1
        if open_idx == -1:
            continue
        while i < len(source) and depth > 0:
            if mask[i]:
                if source[i] == "{":
                    depth += 1
                elif source[i] == "}":
                    depth -= 1
            i += 1
        if depth != 0:
            continue  # unbalanced; skip rather than misattribute
        blocks.append(ContractBlock(name, kind, open_idx, i, source[open_idx + 1:i - 1]))
    return blocks


def extract_contract_names(source: str) -> list[str]:
    """All top-level contract/interface/library names, in source order."""
    return [b.name for b in split_contracts(source)]


def extract_target_name(source: str) -> str:
    """The contract the harness deploys: first concrete contract.

    Falls back to the first block of any kind, then to "Target". (The
    legacy :func:`extract_contract_name` returns the first ``contract``
    keyword match, which may be an un-deployable stub; this is the
    deployability-aware version.)
    """
    blocks = split_contracts(source)
    for b in blocks:
        if b.kind == "contract":
            return b.name
    if blocks:
        return blocks[0].name
    return extract_contract_name(source)


def extract_target_functions(source: str) -> list[FunctionSig]:
    """Function signatures belonging to the deploy-target contract only.

    Weakness-hunt round, target 2: the harness used to wrap EVERY function
    in the file against the single deployed target, so any multi-contract
    file failed to compile (and died silently). Only the target's own
    functions are wrapped now; auxiliary contracts still compile as
    dependencies of the same source file.
    """
    blocks = split_contracts(source)
    target = extract_target_name(source)
    for b in blocks:
        if b.name == target:
            return extract_functions(b.body)
    return extract_functions(source)


def extract_pragma(source: str) -> str:
    """Return the source's pragma line, or a safe default."""
    m = _PRAGMA_RE.search(source)
    if m:
        return f"pragma solidity {m.group(1).strip()};"
    return "pragma solidity ^0.8.20;"


def extract_functions(source: str) -> list[FunctionSig]:
    """Parse top-level function signatures out of Solidity source."""
    sigs: list[FunctionSig] = []
    for m in _FUNC_RE.finditer(source):
        name = m.group(1)
        if name in ("constructor",):
            continue
        raw_params = m.group(2).strip()
        params: list[tuple[str, str]] = []
        if raw_params:
            for i, part in enumerate(raw_params.split(",")):
                tokens = part.strip().split()
                if not tokens:
                    continue
                ptype = tokens[0]
                # Weakness-hunt round, target 3: preserve `payable` in
                # `address payable` parameters. Dropping it produced
                # `target.sweep(p0)` with p0: address against
                # `sweep(address payable to)` — a compile failure.
                rest = tokens[1:]
                if "payable" in rest:
                    ptype += " payable"
                    rest = [t for t in rest if t != "payable"]
                pname = rest[0] if rest else f"p{i}"
                # strip data-location / calldata keywords leaking into the type
                ptype = ptype.replace("calldata", "").replace("memory", "").strip()
                params.append((ptype, re.sub(r"\W", "", pname) or f"p{i}"))
        mutability = (m.group(4) or "").strip()
        sigs.append(FunctionSig(name, params, mutability))
    return sigs


#: The harness deploys the target contract *as* this fixed neutral address
#: (via ``vm.prank`` in the handler constructor), so the harness itself is
#: never the contract's owner. Owner-gated paths stay unreachable to the
#: fuzzer (no owner-confusion false positives), while tx.origin phishing
#: remains testable (see ``act_phishOrigin``). Checksum verified against
#: the pinned Foundry build; also excluded from mined-sender extraction so
#: the fuzzer can never accidentally act as the owner.
NEUTRAL_DEPLOYER = "0x00000000000000000000000000000000DeaDBeef"

#: Cheat-code address: never mined as a sender.
_VM_ADDRESS = "0x7109709ecfa91a80626ff3989d68f67f5b1dd12d"

_MINED_ADDR_RE = re.compile(r"0x[0-9a-fA-F]{40}")


def extract_mined_senders(source: str, limit: int = 8) -> list[str]:
    """Mine hardcoded address literals from the source as candidate senders.

    Restores the old fuzzer's address-mining: a role gated on a hardcoded
    address (e.g. ``pauser = address(0x...dEaD)``) is unreachable to a
    fuzzer that only ever calls as itself. Every distinct non-zero literal
    becomes a sender the harness can impersonate via prank.
    """
    seen: list[str] = []
    for m in _MINED_ADDR_RE.finditer(source):
        addr = m.group(0).lower()
        if addr == "0x" + "0" * 40:
            continue
        if addr in (_VM_ADDRESS, NEUTRAL_DEPLOYER.lower()):
            continue
        if addr not in seen:
            seen.append(addr)
        if len(seen) >= limit:
            break
    return seen


def addr_expr(hex_addr: str) -> str:
    """Render a hex address as Solidity that never trips checksum validation.

    solc ≥0.8.18 rejects 40-hex-char literals with a bad EIP-55 checksum —
    and we cannot compute EIP-55 here (no keccak dependency) — so mined
    addresses render as ``address(uint160(<decimal>))``, which the
    compiler always accepts.
    """
    return f"address(uint160({int(hex_addr, 16)}))"


def sender_pool(
    source: str, bounds: FuzzBounds, *, extra: list[str] | None = None,
) -> list[str]:
    """Ordered sender pool: built-ins, config, mined-from-source, extra.

    ``extra`` (e.g. attacker-contract placeholders) is appended last; the
    handler always seeds slot 0 with itself, so the pool is never empty.
    """
    pool = [
        "address(uint160(0xB0B))",
        "address(uint160(0xC0C))",
        "address(uint160(0xD0D))",
    ]
    for addr in list(bounds.impersonate_senders) + extract_mined_senders(source):
        expr = addr_expr(addr)
        if expr not in pool:
            pool.append(expr)
    for addr in extra or []:
        if addr not in pool:
            pool.append(addr)
    return pool


def _generic_arg_expr(ptype: str, index: int, addr_expr: str = "u") -> str:
    """A deterministic generic argument expression for one parameter type.

    Used by the entry dispatcher (phishing + coverage): argument quality
    does not matter there — the fuzzer's own calls provide variety — so
    every parameter maps to a cheap deterministic expression over the
    dispatcher seeds (``a``/``b``) and an address expression.
    """
    if ptype.startswith("uint"):
        return "a" if index % 2 == 0 else "b"
    if ptype.startswith("int"):
        return f"int256({'a' if index % 2 == 0 else 'b'})"
    if ptype == "bool":
        return "true" if index % 2 == 0 else "false"
    if ptype == "address":
        return addr_expr
    if ptype == "address payable":
        return f"payable({addr_expr})"
    if ptype.startswith("bytes"):
        return f"{ptype}(a)"
    return "a"


#: Weakness-hunt round, target 6: suspicious name fragments, checked
#: first by the deterministic coverage sweep (seed-1337 dilution fix).
_SUSPICIOUS_FN_RE = re.compile(
    r"skim|mint|drain|withdraw|sweep|claim|steal|loot|pillage|"
    r"extract|rescue|recover|emergency|backdoor|selfdestruct|"
    r"suicide|kill|destroy|pause|unpause|upgrade|setOwner|"
    r"transferOwnership|renounce",
    re.IGNORECASE,
)


def coverage_order(
    sigs: list[FunctionSig], invariants: list[Invariant]
) -> list[FunctionSig]:
    """Order entry points suspicious-first for the coverage sweep.

    Functions referenced by invariants and functions with suspicious
    names (skim/mint/drain/...) come first; state-changing before view;
    alphabetical as the final tiebreak (deterministic). The sweep visits
    every entry point regardless — the order only decides what gets hit
    first when the budget is tight.
    """
    inv_fns: set[str] = set()
    for inv in invariants:
        inv_fns.update(inv.functions)
        inv_fns.update(re.findall(r"target\.(\w+)\s*\(", inv.assertion))
        inv_fns.update(re.findall(r"target\.(\w+)\s*\(", inv.statement))
    def key(sig: FunctionSig) -> tuple[int, int, str]:
        s = 0
        if sig.name in inv_fns:
            s += 100
        if _SUSPICIOUS_FN_RE.search(sig.name):
            s += 50
        changing = 1 if sig.mutability in ("nonpayable", "payable") else 0
        return (-s, -changing, sig.name)
    return sorted(sigs, key=key)


def _render_entry_dispatcher(
    contract_name: str,
    entries: list[FunctionSig],
    *,
    via_passthrough: bool,
    chunk_size: int = 256,
) -> str:
    """Render ``_wgCallEntry``: call the k-th target entry point.

    One dispatcher serves the phishing action (target 1: tx.origin with
    ``msg.sender != tx.origin``) and — from the weakness-hunt round's
    target 6 — the deterministic coverage sweep. Every leaf swallows
    reverts: the goal is to *attempt* the call, never to require success.

    ``via_passthrough=True`` (ghost mode) routes through the handler's own
    passthroughs so ghost accounting stays in lockstep; ``False`` (attack
    mode) calls the target directly inside try/catch.
    """
    n = len(entries)
    addr_expr = "_wgPickSender(a)" if via_passthrough else "u"
    chunks: list[str] = []
    for ci in range(0, n, chunk_size):
        chunk = entries[ci:ci + chunk_size]
        lines = [
            f"    function _wgEntryChunk{ci // chunk_size}"
            "(uint256 idx, address u, uint256 a, uint256 b, uint256 s) internal {"
        ]
        for j, fn in enumerate(chunk):
            k = ci + j
            args = ", ".join(
                _generic_arg_expr(t, i, addr_expr)
                for i, (t, _) in enumerate(fn.params)
            )
            if via_passthrough:
                args = ", ".join(([args] if args else []) + ["s"])
                call = f"this.{fn.name}({args})"
                if fn.mutability == "payable":
                    call = f"this.{fn.name}{{value: 0}}({args})"
            else:
                call = f"target.{fn.name}({args})"
                if fn.mutability == "payable":
                    call = f"target.{fn.name}{{value: 0}}({args})"
            lines.append(f"        if (idx == {k}) {{ try {call} {{}} catch {{}} return; }}")
        lines.append("    }")
        chunks.append("\n".join(lines))
    dispatch = [
        "    // Call the k-th target entry point (mod entry count).",
        "    // Shared by the phishing action and the coverage sweep.",
        f"    uint256 constant WG_ENTRY_COUNT = {n};",
        "    function _wgCallEntry(uint256 k, address u, uint256 a, uint256 b, uint256 s) internal {",
        "        if (WG_ENTRY_COUNT == 0) return;",
        "        uint256 idx = k % WG_ENTRY_COUNT;",
    ]
    for ci in range(0, n, chunk_size):
        dispatch.append(
            f"        if (idx < {ci + chunk_size}) {{ _wgEntryChunk{ci // chunk_size}(idx, u, a, b, s); return; }}"
        )
    dispatch.append("    }")
    return "\n".join(dispatch + [""] + chunks)


# ---------------------------------------------------------------------------
# Shared rendering bits
# ---------------------------------------------------------------------------


def _sanitize_fn(name: str) -> str:
    clean = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if clean and clean[0].isdigit():
        clean = "inv_" + clean
    return clean or "inv_unnamed"


def _render_invariant(inv: Invariant) -> str:
    fn = _sanitize_fn("invariant_" + inv.id)
    stmt = inv.statement.replace("*/", "* /").replace("\n", " ")
    assertion = " ".join(inv.assertion.split())
    return (
        f"    // {inv.id} [{inv.bug_class}, {inv.source}]: {stmt}\n"
        f"    function {fn}() public view {{\n"
        f"        assert({assertion});\n"
        f"    }}"
    )


def _render_toml(bounds: FuzzBounds, depth: int, attack: bool) -> str:
    kind = "attack" if attack else "plain"
    seed_hex = f"0x{bounds.seed & ((1 << 256) - 1):x}"
    return f"""\
# Web3Guard-generated foundry.toml ({kind} harness).
# Generated by our renderer -- never by the LLM -- so it is trusted input.
# Hardened: no ffi, no filesystem access for the fuzzed code.
# seed: fixed campaign seed (reproducible runs; also passed as
# `forge test --fuzz-seed` and baked into the handler's strategy PRNG).
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
auto_detect_solc = true
ffi = false
fs_permissions = []

[invariant]
runs = {bounds.runs}
depth = {depth}
fail_on_revert = {"true" if bounds.fail_on_revert else "false"}

[fuzz]
seed = "{seed_hex}"
"""


# ---------------------------------------------------------------------------
# Plain (legacy) renderer — moneyless direct-call fuzzing, kept for baselining
# ---------------------------------------------------------------------------


def _render_plain_project(
    contract_source: str,
    contract_name: str,
    invariants: list[Invariant],
    bounds: FuzzBounds,
) -> dict[str, str]:
    """Render the legacy harness: target deployed in setUp(), no handler."""
    test_parts: list[str] = [
        "// SPDX-License-Identifier: MIT",
        extract_pragma(contract_source),
        "",
        "// Web3Guard-generated invariant harness (plain/legacy mode).",
        "// Foundry's invariant engine automatically targets every contract",
        "// deployed in setUp() and fuzzes its public functions with random",
        "// inputs and senders; each invariant_* function below must hold",
        "// after every call sequence. No forge-std dependency is needed.",
        f'import "../src/{contract_name}.sol";',
        "",
        "contract InvariantTest {",
        f"    {contract_name} public target;",
        "",
        "    function setUp() public {",
        f"        target = new {contract_name}();",
        "    }",
        "",
    ]

    if invariants:
        test_parts.append("    // --- invariants under test ---")
        for inv in invariants:
            test_parts.append(_render_invariant(inv))
            test_parts.append("")
    else:
        test_parts.append("    // NOTE: no invariants applied; nothing to assert.")
        test_parts.append("")

    test_parts.append("}")
    test_src = "\n".join(test_parts) + "\n"

    return {
        "foundry.toml": _render_toml(bounds, bounds.depth, attack=False),
        f"src/{contract_name}.sol": contract_source,
        "test/Invariant.t.sol": test_src,
    }


# ---------------------------------------------------------------------------
# Attack renderer — the simulator learns to actually attack
# ---------------------------------------------------------------------------

#: Handler action names reserved by the attack harness; a target function
#: whose action would collide is skipped (with a note) rather than
#: emitting uncompilable Solidity.
_RESERVED_ACTIONS = {
    "attack_reenter",
    "donateForcedEth",
    "warpTime",
    "heist",
    "adaptiveAssault",
    "approvalDrain",
    "vaultCycle",
    "phishOrigin",
}


def _generic_action(fn: FunctionSig) -> str:
    """A value-carrying handler action for one target function.

    The ETH value comes from a fuzzed ``uint256`` parameter (clamped),
    never from the engine's msg.value, so every payable path is exercised
    with real money on every campaign.
    """
    params = ", ".join(f"{t} p{i}" for i, (t, _) in enumerate(fn.params))
    args = ", ".join(f"p{i}" for i in range(len(fn.params)))
    sig_params = ", ".join(([params] if params else []) + ["uint256 _wgValue", "uint256 _wgUser"])
    lines = [f"    function act_{fn.name}({sig_params}) public {{"]
    lines.append("        address u = _wgPickSender(_wgUser);")
    if fn.mutability == "payable":
        lines.append("        uint256 v = _wgCap(_wgValue);")
        lines.append("        WGVM.prank(u);")
        # NB: call options attach directly: target.deposit{value: v}().
        lines.append(f"        target.{fn.name}{{value: v}}({args});")
    else:
        lines.append("        WGVM.prank(u);")
        lines.append(f"        target.{fn.name}({args});")
    lines.append("    }")
    return "\n".join(lines)


def _render_attack_project(
    contract_source: str,
    contract_name: str,
    invariants: list[Invariant],
    bounds: FuzzBounds,
) -> dict[str, str]:
    """Render the attack harness (default): handler + attacker contracts."""
    pragma = extract_pragma(contract_source)
    functions = extract_target_functions(contract_source)
    specs, attacker_notes = _attackers.select_attackers(pragma, functions)
    weights, primary, _planned, _selector = _strategies.plan_campaign(
        contract_source,
        functions,
        epsilon=bounds.strategy_epsilon,
        seed=bounds.seed,
    )

    vault = _attackers.detect_vault_interface(functions)
    by_name = {fn.name: fn for fn in functions}
    dep_fn = by_name.get(vault.deposit_fn) if vault else None
    # Canonical ETH-vault shape the scripted attacks can drive: a payable
    # deposit() taking no arguments plus a withdraw(uint256).
    eth_vault = bool(
        vault is not None
        and dep_fn is not None
        and dep_fn.mutability == "payable"
        and not dep_fn.params
    )
    approve_fn = next(
        (
            fn
            for fn in functions
            if fn.name.lower() == "approve"
            and len(fn.params) == 2
            and fn.params[0][0] == "address"
            and fn.params[1][0].startswith("uint")
        ),
        None,
    )
    has_drainer = any(s.name == "ApprovalDrainer" for s in specs)
    render_drain = has_drainer and approve_fn is not None

    notes: list[str] = list(attacker_notes)
    if vault is not None and not eth_vault:
        notes.append(
            f"vault-like pair ({vault.deposit_sig}, {vault.withdraw_sig}) "
            "detected but the deposit is not a no-arg payable function: "
            "scripted reentrancy/heist actions are disabled for this target"
        )
    if has_drainer and approve_fn is None:
        notes.append(
            "approval drainer deployed but no standard approve(address,uint) "
            "found: the approval-drain action is disabled for this target"
        )
    # Weakness-hunt round, target 5: if any invariant is time-limited,
    # disable time-warp actions (warping past the window is a false
    # positive, not a bug).
    from web3guard.invariants.templates import infer_temporal_scope

    warp_disabled = any(
        inv.temporal_scope == "time-limited"
        or infer_temporal_scope(inv) == "time-limited"
        for inv in invariants
    )
    if warp_disabled:
        notes.append(
            "attack harness: time-warp actions DISABLED — a time-limited "
            "invariant is active; warping the clock would manufacture a "
            "false positive."
        )

    # -- handler action functions --------------------------------------
    action_fns: list[str] = []
    seen_actions: set[str] = set()

    def add_action(name: str, body: str) -> None:
        # Weakness-hunt round, target 6: every action piggybacks one
        # deterministic coverage step (seed-1337 dilution fix). Inserted
        # before the function's closing brace.
        if name not in seen_actions:
            seen_actions.add(name)
            if body.rstrip().endswith("}"):
                idx = body.rstrip().rfind("\n    }")
                if idx != -1:
                    body = (
                        body[:idx]
                        + "\n        _wgCoverageStep();"
                        + body[idx:]
                    )
            action_fns.append(body)

    for fn in functions:
        if not fn.fuzzable or fn.name in _RESERVED_ACTIONS:
            continue
        add_action(f"act_{fn.name}", _generic_action(fn))

    if eth_vault and vault is not None:
        dep, wd = vault.deposit_fn, vault.withdraw_fn
        wd_sig = vault.withdraw_sig
        add_action(
            "act_vaultCycle",
            f"""    // value-heavy: coherent deposit -> (partial) withdraw cycle.
    function act_vaultCycle(uint256 _wgValue, uint256 _wgFrac, uint256 _wgUser) public {{
        address u = _wgPickSender(_wgUser);
        uint256 v = _wgCap(_wgValue);
        WGVM.prank(u);
        target.{dep}{{value: v}}();
        uint256 w = (v * (_wgFrac % 101)) / 100;
        if (w > 0) {{
            WGVM.prank(u);
            target.{wd}(w);
        }}
    }}""",
        )

    if not warp_disabled:
        add_action(
            "act_warpTime",
            """    // time-warped: advance the clock / block height, then keep attacking.
    // Exposes vm.warp + vm.roll as fuzzed attack actions (vesting, TWAP,
    // lockups, deadlines).
    function act_warpTime(uint256 _wgSecs, uint256 _wgBlocks) public {
        WGVM.warp(block.timestamp + (_wgSecs % 365 days));
        WGVM.roll(block.number + (_wgBlocks % 100000));
    }""",
        )

    add_action(
        "act_donateForcedEth",
        """    // value-heavy: force-feed ETH past receive()/fallback via selfdestruct.
    // Breaks any naive `balance == deposits - withdrawals` accounting.
    function act_donateForcedEth(uint256 _wgValue) public {
        _wgFundAttacker(address(donationAttacker), _wgCap(_wgValue));
        if (address(donationAttacker).balance > 0) {
            donationAttacker.donate(payable(address(target)));
        }
    }""",
    )

    # Phishing action (weakness-hunt round, target 1): the tx.origin threat
    # model. The neutral owner is tricked into interacting with a malicious
    # contract; the target sees msg.sender = <pool sender> (a contract or a
    # user that is NOT the owner) with tx.origin = owner. On a clean
    # contract (msg.sender-based auth) every such call reverts; on a
    # tx.origin-authed contract the check passes and the money-flow
    # invariants catch the theft. Routes through the entry dispatcher so
    # any target function can be the phished call.
    # Weakness-hunt round, target 6: suspicious-first ordering for the
    # deterministic coverage sweep (seed-1337 dilution fix).
    dispatcher_entries = coverage_order(
        [fn for fn in functions if fn.fuzzable], invariants
    )
    add_action(
        "act_phishOrigin",
        """    // phishing model for tx.origin bugs (see header): msg.sender is a
    // pool sender, tx.origin is the neutral owner. Clean contracts revert;
    // tx.origin-authed contracts let the call through.
    function act_phishOrigin(uint256 _wgFn, uint256 _wgA, uint256 _wgB, uint256 _wgUser) public {
        address u = _wgPickSender(_wgUser);
        WGVM.prank(u, WG_NEUTRAL_DEPLOYER);
        _wgCallEntry(_wgFn, u, _wgA, _wgB, _wgUser);
        _wgCoverageStep();
    }""",
    )
    dispatcher_src = _render_entry_dispatcher(
        contract_name, dispatcher_entries, via_passthrough=False,
    )
    mined = extract_mined_senders(contract_source)
    if mined:
        notes.append(
            "sender impersonation: mined from source: " + ", ".join(mined)
        )

    if render_drain and approve_fn is not None:
        add_action(
            "act_approvalDrain",
            f"""    // attacker-contract: victim approves the drainer, drainer pulls via transferFrom.
    function act_approvalDrain(uint256 _wgAmount, uint256 _wgUser) public {{
        if (address(approvalDrainer) == address(0)) return;
        address victim = _wgPickSender(_wgUser);
        WGVM.prank(victim);
        target.{approve_fn.name}(address(approvalDrainer), type(uint256).max);
        approvalDrainer.drain(address(target), victim, _wgAmount);
    }}""",
        )

    core_fns: list[str] = []
    # Weakness-hunt round, target 5: the heist's time-warp step and the
    # bandit's warp mode are omitted when a time-limited invariant is
    # active (warping would be a false positive).
    _warp_heist = (
        "        WGVM.warp(block.timestamp + ((warpDays % 30) * 1 days));\n"
        if not warp_disabled else ""
    )
    _warp_bandit = (
        "            WGVM.warp(block.timestamp + ((_wgA % 30) * 1 days));\n"
        if not warp_disabled else ""
    )
    if eth_vault and vault is not None:
        dep, wd = vault.deposit_fn, vault.withdraw_fn
        wd_sig = vault.withdraw_sig
        core_fns.append(
            f"""    // Core reentrancy attack, shared by act_attack_reenter, act_heist and
    // the adaptive bandit. Victim money goes in first (there must be
    // something to steal), the attacker is funded (ghost-accounted), then
    // the handler withdraws AS the attacker contract so receive()
    // re-enters the target mid-call.
    function _wgDoReenter(uint256 v, uint256 userSeed) internal {{
        if (address(reenterAttacker) == address(0) || v == 0) return;
        address a = address(reenterAttacker);
        WGVM.prank(_wgPickSender(userSeed));
        target.{dep}{{value: v}}();
        _wgFundAttacker(a, v);
        reenterAttacker.arm(
            address(target),
            abi.encodeWithSignature("{wd_sig}", v),
            3
        );
        WGVM.prank(a);
        target.{dep}{{value: v}}();
        WGVM.prank(a);
        target.{wd}(v);
        reenterAttacker.disarm();
    }}

    // attacker-contract strategy: single-action reentrancy strike.
    function act_attack_reenter(uint256 _wgValue, uint256 _wgSeed) public {{
        _wgDoReenter(_wgCap(_wgValue), _wgSeed);
    }}

    // multi-step strategy: the full heist inside ONE fuzzed action --
    // victim deposit -> time warp -> attacker deposit -> reentrant drain
    // -> donation kicker. Well beyond the old 15-call ceiling per action,
    // and the campaign depth (see foundry.toml) allows long sequences
    // of these to chain.
    function _wgDoHeist(uint256 v, uint256 warpDays, uint256 userSeed) internal {{
        if (v == 0) return;
        WGVM.prank(_wgPickSender(userSeed));
        target.{dep}{{value: v}}();
{_warp_heist}        _wgDoReenter(v, userSeed + 1);
        uint256 dust = v / 100;
        if (dust > 0 && address(donationAttacker).balance == 0) {{
            _wgFundAttacker(address(donationAttacker), dust);
            donationAttacker.donate(payable(address(target)));
        }}
    }}

    function act_heist(uint256 _wgValue, uint256 _wgWarpDays, uint256 _wgSeed) public {{
        _wgDoHeist(_wgCap(_wgValue), _wgWarpDays, _wgSeed);
    }}

    // mixed strategy: on-chain epsilon-greedy bandit over the attack modes
    // (0 direct-value, 1 reentrant, 2 time-warped, 3 heist). Each call picks
    // a mode -- usually the best-scoring one, sometimes a random one -- and
    // reinforces the mode with the real profit the attacker contracts
    // extracted. Seeded by WG_CAMPAIGN_SEED, so it reproduces per campaign.
    function act_adaptiveAssault(uint256 _wgSeed, uint256 _wgA, uint256 _wgB) public {{
        uint256 r = uint256(keccak256(abi.encode(WG_CAMPAIGN_SEED, _wgSeed, wgModePulls))) % 100;
        uint256 mode;
        if (r < WG_BANDIT_EXPLORE_PCT) {{
            mode = _wgSeed % 4;
        }} else {{
            mode = 0;
            for (uint256 i = 1; i < 4; i++) {{
                if (wgModeScore[i] > wgModeScore[mode]) {{
                    mode = i;
                }}
            }}
        }}
        uint256 beforeFunds = _wgAttackerFunds();
        if (mode == 0) {{
            WGVM.prank(_wgPickSender(_wgA));
            target.{dep}{{value: _wgCap(_wgB)}}();
        }} else if (mode == 1) {{
            _wgDoReenter(_wgCap(_wgA), _wgB);
        }} else if (mode == 2) {{
{_warp_bandit}            WGVM.prank(_wgPickSender(_wgB));
            target.{dep}{{value: _wgCap(_wgA)}}();
        }} else {{
            _wgDoHeist(_wgCap(_wgA), _wgB, _wgA);
        }}
        uint256 afterFunds = _wgAttackerFunds();
        if (afterFunds > beforeFunds) {{
            wgModeScore[mode] += (afterFunds - beforeFunds);
        }}
        wgModePulls += 1;
    }}"""
        )

    # -- constructor deployment lines ----------------------------------
    # Neutral deployment: the target is deployed as WG_NEUTRAL_DEPLOYER
    # (pranked in the constructor body, rendered below) so the harness is
    # never the contract's owner. Attacker contracts deploy as the handler
    # itself, as before.
    deploy_attackers = [
        "donationAttacker = new DonationAttacker();",
    ]
    if any(s.name == "ReentrancyAttacker" for s in specs):
        deploy_attackers.append("reenterAttacker = new ReentrancyAttacker();")
    if any(s.name == "ApprovalDrainer" for s in specs):
        deploy_attackers.append("approvalDrainer = new ApprovalDrainer();")

    # Sender pool: the handler itself first (never empty), then built-in
    # users, operator-configured senders, and addresses mined from source.
    pool_addrs = ["address(this)"] + sender_pool(contract_source, bounds)

    feature_list = (
        ", ".join(
            sorted(
                f
                for f, on in _strategies.contract_features(contract_source, functions).items()
                if on
            )
        )
        or "(none)"
    )
    weight_list = " ".join(f"{name}={w}" for name, w in sorted(weights.items()))
    header_notes = "\n".join(f"//   - {n}" for n in notes)

    attacker_imports = "\n".join(
        f'import "./attackers/{name}.sol";'
        for name in ("DonationAttacker", "ReentrancyAttacker", "ApprovalDrainer")
    )

    handler_src = f"""// SPDX-License-Identifier: MIT
{pragma}

// Web3Guard ATTACK harness (Phase 1 upgrade). The old simulator could only
// make simple moneyless direct calls; this handler teaches it to ATTACK:
//   * value-carrying actions -- every target function gets a handler action
//     whose ETH value is drawn from the fuzzer's input space (the handler
//     is pre-funded; amounts clamp to WG_MAX_CALL_VALUE);
//   * attacker contracts -- deployed below and driven THROUGH, not around;
//   * multi-step heists -- act_heist runs deposit -> warp -> reenter ->
//     drain (+ donation kicker) inside one fuzzed action;
//   * time manipulation -- act_warpTime exposes vm.warp / vm.roll;
//   * adaptive strategy -- act_adaptiveAssault runs an on-chain
//     epsilon-greedy bandit over the attack modes, reinforced by real
//     extracted profit.
// Strategy plan for this target (selector: epsilon-greedy bandit):
//   primary: {primary.name} (epsilon={bounds.strategy_epsilon}, seed={bounds.seed})
//   weights: {weight_list}
//   features: {feature_list}
//   attackers: {", ".join(s.name for s in specs)}
{header_notes if header_notes else "//   (no warnings)"}
// WG-STRATEGIES: {",".join(s.name for s in _strategies.PORTFOLIO)}
// WG-PRIMARY-STRATEGY: {primary.name}
// WG-CAMPAIGN-SEED: {bounds.seed}
// NOTE: forge-std-free by design -- cheatcodes are reached through the
// hard-coded VM address, so the project builds with zero downloads.
import "../src/{contract_name}.sol";
{attacker_imports}

interface WgVm {{
    function deal(address account, uint256 newBalance) external;
    function warp(uint256 newTimestamp) external;
    function roll(uint256 newHeight) external;
    function prank(address msgSender) external;
    function prank(address msgSender, address txOrigin) external;
}}

// The HEVM cheat-code address (hard-coded, as in forge-std; this is the
// documented Foundry cheatcode address, not keccak-derived at runtime).
WgVm constant WGVM = WgVm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);

// Neutral deployer (weakness-hunt round, target 1): the handler deploys the
// target *as* this fixed address, so the harness is never the contract's
// owner. Owner-gated paths stay unreachable to the fuzzer (no
// owner-confusion false positives), while tx.origin phishing remains
// testable via act_phishOrigin below.
address constant WG_NEUTRAL_DEPLOYER = address(0x00000000000000000000000000000000DeaDBeef);

contract AttackHandler {{
    {contract_name} public target;
    DonationAttacker public donationAttacker;
    ReentrancyAttacker public reenterAttacker;
    ApprovalDrainer public approvalDrainer;

    // Ghost accounting: every wei the harness ever dealt to an attacker.
    // invariant_attacker_no_profit asserts the attackers never hold more.
    uint256 public totalAttackerFunding;

    // Deterministic coverage sweep (weakness-hunt round, target 6):
    // persistent cursor through the entry points (suspicious-first order),
    // advanced by one on every action. Independent of the fuzzer's seed.
    uint256 public wgCoverageCursor;
    bool internal _wgCovering;

    // Sender pool (weakness-hunt round, target 1): every address the
    // harness may act as — built-in users, operator-configured senders,
    // and addresses mined from the target source (e.g. a hardcoded pauser).
    // Slot 0 is always the handler itself, so the pool is never empty.
    // The neutral deployer is deliberately NOT in the pool: the fuzzer
    // must never act as the owner.
    address[] public wgSenderPool;

    // On-chain epsilon-greedy bandit state (the "mixed" strategy).
    uint256[4] public wgModeScore;
    uint256 public wgModePulls;

    uint256 constant WG_CAMPAIGN_SEED = {bounds.seed & ((1 << 256) - 1)};
    uint256 constant WG_MAX_CALL_VALUE = {bounds.attack_max_value_wei};
    uint256 constant WG_BANDIT_EXPLORE_PCT = {int(bounds.strategy_epsilon * 100)};

    receive() external payable {{}}

    constructor() {{
        // Neutral deployment (see above): prank is one-shot, so only the
        // target deployment is affected; attacker contracts deploy as the
        // handler itself, exactly as before.
        WGVM.prank(WG_NEUTRAL_DEPLOYER);
        target = new {contract_name}();
{chr(10).join("        " + line for line in deploy_attackers)}
{chr(10).join("        wgSenderPool.push(" + a + ");" for a in pool_addrs)}
        WGVM.deal(address(this), 100000 ether);
        for (uint256 _wgi = 0; _wgi < wgSenderPool.length; _wgi++) {{
            WGVM.deal(wgSenderPool[_wgi], 10000 ether);
        }}
    }}

    function _wgCap(uint256 v) internal pure returns (uint256) {{
        return v % (WG_MAX_CALL_VALUE + 1);
    }}

    function _wgPickSender(uint256 i) internal view returns (address) {{
        return wgSenderPool[i % wgSenderPool.length];
    }}

    function _wgAttackerFunds() internal view returns (uint256) {{
        return address(reenterAttacker).balance
            + address(donationAttacker).balance
            + address(approvalDrainer).balance;
    }}

    function _wgFundAttacker(address a, uint256 v) internal {{
        if (v == 0) return;
        WGVM.deal(a, a.balance + v);
        totalAttackerFunding += v;
    }}

    // Deterministic coverage sweep (weakness-hunt round, target 6):
    // piggybacked on every action, advances a persistent cursor through
    // the entry points (suspicious-first order) independent of the seed.
    // The _wgCovering guard prevents recursion.
    function _wgCoverageStep() internal {{
        if (_wgCovering) return;
        if (wgCoverageCursor >= WG_ENTRY_COUNT) return;
        _wgCovering = true;
        _wgCallEntry(wgCoverageCursor, address(0), wgCoverageCursor, wgCoverageCursor, wgCoverageCursor);
        wgCoverageCursor += 1;
        _wgCovering = false;
    }}

{chr(10).join(core_fns)}

{chr(10).join(action_fns)}

{dispatcher_src}
}}
"""

    test_parts: list[str] = [
        "// SPDX-License-Identifier: MIT",
        pragma,
        "",
        "// Web3Guard attack-harness test contract (Phase 1 upgrade).",
        "// Only the AttackHandler is deployed in setUp() -- it is the only",
        "// contract Foundry's invariant engine fuzzes. The target and the",
        "// attacker contracts are deployed inside the handler's constructor.",
        f"// WG-STRATEGY-WEIGHTS: {weight_list}",
        f"// WG-STRATEGIES: {','.join(s.name for s in _strategies.PORTFOLIO)}",
        f"// WG-PRIMARY-STRATEGY: {primary.name}",
        f"// WG-CAMPAIGN-SEED: {bounds.seed}",
        f'import "../src/{contract_name}.sol";',
        'import "./AttackHandler.sol";',
        "",
        "contract InvariantTest {",
        "    AttackHandler public handler;",
        f"    {contract_name} public target;",
        "",
        "    function setUp() public {",
        "        handler = new AttackHandler();",
        f"        target = {contract_name}(address(handler.target()));",
        "    }",
        "",
    ]

    if invariants:
        test_parts.append("    // --- invariants under test ---")
        for inv in invariants:
            test_parts.append(_render_invariant(inv))
            test_parts.append("")
    else:
        test_parts.append("    // NOTE: no invariants applied; nothing to assert.")
        test_parts.append("")

    test_parts.extend(
        [
            "    // --- harness-level invariant (attack simulator) ---",
            "    // attacker-no-profit [exploit]: the attacker contracts must never",
            "    // hold more ETH than the harness funded them with. A violation",
            "    // means an exploit extracted value; the call sequence below is",
            "    // the machine-checked proof of concept.",
            "    function invariant_attacker_no_profit() public view {",
            "        uint256 held = address(handler.reenterAttacker()).balance",
            "            + address(handler.donationAttacker()).balance",
            "            + address(handler.approvalDrainer()).balance;",
            "        assert(held <= handler.totalAttackerFunding());",
            "    }",
            "",
        ]
    )
    test_parts.append("}")
    test_src = "\n".join(test_parts) + "\n"

    files: dict[str, str] = {
        "foundry.toml": _render_toml(bounds, bounds.effective_depth, attack=True),
        f"src/{contract_name}.sol": contract_source,
        "test/Invariant.t.sol": test_src,
        "test/AttackHandler.sol": handler_src,
    }
    for name, generator in (
        ("DonationAttacker", _attackers.donation_attacker_source),
        ("ReentrancyAttacker", _attackers.reentrancy_attacker_source),
        ("ApprovalDrainer", _attackers.approval_drainer_source),
    ):
        files[f"test/attackers/{name}.sol"] = generator(pragma)
    if notes:
        LOGGER.info("attack harness for %s: %s", contract_name, "; ".join(notes))
    return files


# ---------------------------------------------------------------------------
# Dispatcher + renderer registry (Phase 6 plugs new languages in here)
# ---------------------------------------------------------------------------


def render_solidity_project(
    contract_source: str,
    contract_name: str,
    invariants: list[Invariant],
    bounds: FuzzBounds,
    *,
    attack: bool | None = None,
) -> dict[str, str]:
    """Render a complete Foundry project as {relative_path: content}.

    ``attack=None`` (default) follows ``bounds.attack_enabled`` — ON by
    default, so the pipeline gets the attacking simulator with no changes.
    Pass ``attack=False`` for the legacy plain harness (baselining), or
    ``attack=True`` to force the attack harness.
    """
    use_attack = bounds.attack_enabled if attack is None else bool(attack)
    if use_attack:
        return _render_attack_project(contract_source, contract_name, invariants, bounds)
    return _render_plain_project(contract_source, contract_name, invariants, bounds)


Renderer = Callable[[str, str, list[Invariant], FuzzBounds], dict[str, str]]

_RENDERERS: dict[str, Renderer] = {}


def register_renderer(language: str, renderer: Renderer) -> None:
    """Register a harness renderer for a language (Phase 6 extension point)."""
    _RENDERERS[language.lower()] = renderer


register_renderer("solidity", render_solidity_project)


def render_project(
    language: str,
    contract_source: str,
    contract_name: str,
    invariants: list[Invariant],
    bounds: FuzzBounds,
) -> dict[str, str]:
    """Render a fuzz project for ``language`` via its registered renderer."""
    renderer = _RENDERERS.get(language.lower())
    if renderer is None:
        raise ValueError(
            f"no invariant harness renderer for language {language!r} "
            f"(registered: {sorted(_RENDERERS)})"
        )
    return renderer(contract_source, contract_name, invariants, bounds)


def write_project(project_dir: Path, files: Mapping[str, str]) -> None:
    """Write a rendered project to disk."""
    for rel, content in files.items():
        dest = project_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content)
    LOGGER.info("wrote invariant harness project to %s (%d files)", project_dir, len(files))
